// frontend/src/components/ui/pagination.tsx
import * as React from 'react';
import { ChevronLeftIcon, ChevronRightIcon, MoreHorizontalIcon } from 'lucide-react';

import { cn } from '@/lib/utils';
import { Button, buttonVariants } from '@/components/ui/button';

function Pagination({ className, ...props }: React.ComponentProps<'nav'>) {
  return (
    <nav
      role="navigation"
      aria-label="pagination"
      data-slot="pagination"
      className={cn('mx-auto flex w-full justify-center', className)}
      {...props}
    />
  );
}

function PaginationContent({ className, ...props }: React.ComponentProps<'ul'>) {
  return <ul data-slot="pagination-content" className={cn('flex flex-row items-center gap-1', className)} {...props} />;
}

function PaginationItem({ ...props }: React.ComponentProps<'li'>) {
  return <li data-slot="pagination-item" {...props} />;
}

type PaginationLinkProps = {
  isActive?: boolean;
} & Pick<React.ComponentProps<typeof Button>, 'size'> &
  React.ComponentProps<'a'>;

function PaginationLink({ className, isActive, size = 'icon', ...props }: PaginationLinkProps) {
  return (
    <a
      aria-current={isActive ? 'page' : undefined}
      data-slot="pagination-link"
      data-active={isActive}
      className={cn(
        buttonVariants({
          variant: isActive ? 'outline' : 'ghost',
          size,
        }),
        className
      )}
      {...props}
    />
  );
}

function PaginationPrevious({ className, ...props }: React.ComponentProps<typeof PaginationLink>) {
  return (
    <PaginationLink aria-label="Go to previous page" size="default" className={cn('gap-1 px-2.5 sm:pl-2.5', className)} {...props}>
      <ChevronLeftIcon />
      <span className="hidden sm:block">Previous</span>
    </PaginationLink>
  );
}

function PaginationNext({ className, ...props }: React.ComponentProps<typeof PaginationLink>) {
  return (
    <PaginationLink aria-label="Go to next page" size="default" className={cn('gap-1 px-2.5 sm:pr-2.5', className)} {...props}>
      <span className="hidden sm:block">Next</span>
      <ChevronRightIcon />
    </PaginationLink>
  );
}

function PaginationEllipsis({ className, ...props }: React.ComponentProps<'span'>) {
  return (
    <span aria-hidden data-slot="pagination-ellipsis" className={cn('flex size-9 items-center justify-center', className)} {...props}>
      <MoreHorizontalIcon className="size-4" />
      <span className="sr-only">More pages</span>
    </span>
  );
}

export { Pagination, PaginationContent, PaginationLink, PaginationItem, PaginationPrevious, PaginationNext, PaginationEllipsis };

// frontend/src/lib/components/ui/pagination/pagination.svelte
<script lang="ts">
	import Button from "$lib/components/ui/button/button.svelte";
	import ChevronLeftIcon from "@lucide/svelte/icons/chevron-left";
	import ChevronRightIcon from "@lucide/svelte/icons/chevron-right";
	import MoreHorizontalIcon from "@lucide/svelte/icons/more-horizontal";
	import { cn } from "$lib/utils";

	let {
		class: className,
		totalPages = 1,
		currentPage = $bindable(1),
		onPageChange,
		showPrevNext = true,
		maxVisible = 7,
		...restProps
	}: {
		class?: string;
		totalPages: number;
		currentPage?: number;
		onPageChange?: (page: number) => void;
		showPrevNext?: boolean;
		maxVisible?: number;
	} = $props();

	function handlePageChange(page: number) {
		if (page >= 1 && page <= totalPages && page !== currentPage) {
			currentPage = page;
			onPageChange?.(page);
		}
	}

	function getVisiblePages() {
		if (totalPages <= maxVisible) {
			return Array.from({ length: totalPages }, (_, i) => i + 1);
		}

		const halfVisible = Math.floor((maxVisible - 3) / 2); // -3 for first, last, and ellipsis
		let start = Math.max(currentPage - halfVisible, 2);
		let end = Math.min(currentPage + halfVisible, totalPages - 1);

		if (currentPage <= halfVisible + 1) {
			end = maxVisible - 2;
		}
		if (currentPage >= totalPages - halfVisible) {
			start = totalPages - maxVisible + 3;
		}

		const pages = [];
		
		// Always show first page
		pages.push(1);
		
		// Add ellipsis if needed
		if (start > 2) {
			pages.push(-1); // -1 represents ellipsis
		}
		
		// Add visible pages
		for (let i = start; i <= end; i++) {
			if (i > 1 && i < totalPages) {
				pages.push(i);
			}
		}
		
		// Add ellipsis if needed
		if (end < totalPages - 1) {
			pages.push(-2); // -2 represents ellipsis
		}
		
		// Always show last page (if more than 1 page)
		if (totalPages > 1) {
			pages.push(totalPages);
		}
		
		return pages;
	}

	const visiblePages = $derived(getVisiblePages());
</script>

<nav
	class={cn("mx-auto flex w-full justify-center", className)}
	aria-label="페이지네이션"
	{...restProps}
>
	<div class="flex flex-row items-center gap-1">
		{#if showPrevNext}
			<Button
				variant="outline"
				size="sm"
				class="gap-1 pl-2.5"
				disabled={currentPage <= 1}
				onclick={() => handlePageChange(currentPage - 1)}
			>
				<ChevronLeftIcon class="h-4 w-4" />
				<span>이전</span>
			</Button>
		{/if}

		{#each visiblePages as page}
			{#if page === -1 || page === -2}
				<span class="flex h-9 w-9 items-center justify-center">
					<MoreHorizontalIcon class="h-4 w-4" />
					<span class="sr-only">더 많은 페이지</span>
				</span>
			{:else}
				<Button
					variant={page === currentPage ? "default" : "outline"}
					size="sm"
					class="h-9 w-9"
					onclick={() => handlePageChange(page)}
				>
					{page}
				</Button>
			{/if}
		{/each}

		{#if showPrevNext}
			<Button
				variant="outline"
				size="sm"
				class="gap-1 pr-2.5"
				disabled={currentPage >= totalPages}
				onclick={() => handlePageChange(currentPage + 1)}
			>
				<span>다음</span>
				<ChevronRightIcon class="h-4 w-4" />
			</Button>
		{/if}
	</div>
</nav>
